name: Sanity Check
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - labeled
      - unlabeled

jobs:
  pr_wip_check:
    runs-on: ubuntu-latest
    name: WIP Check
    steps:
    - name: WIP Check
      uses: Tim-Zhang/wip-check@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        labels: '["do-not-merge", "wip", "rfc"]'
        keywords: '["WIP", "wip", "RFC", "rfc"]'
